apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkIn
spec:
  selector:
    matchLabels:
      run: checkIn
  replicas: 1
  template:
    metadata:
      labels:
        run: checkIn
    spec:
      containers:
        - name: checkIn
          image: k8s.gcr.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: checkIn
  labels:
    app: checkIn
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: checkIn